"""booking comments

Revision ID: fa66ae029015
Revises: 4eb45d9e0afa
Create Date: 2021-03-22 22:31:07.391225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa66ae029015'
down_revision = '4eb45d9e0afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slot', schema=None) as batch_op:
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
